import { useMemo, useState } from "react";
import { Link, useHydrated } from "@tanstack/react-router";
import { AlertCircle, ArrowRight, Braces, CheckCircle2, Clipboard, CloudOff, Database, LoaderCircle, Play, RefreshCw, Search, ShieldAlert, Sparkles } from "lucide-react";
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip as ChartTooltip, XAxis, YAxis } from "recharts";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { PageHeading } from "@/components/layout/app-shell";
import { PipelineTimeline } from "@/components/science/pipeline-timeline";
import { ForecastTimeline, LossChart, MeshField, MetricTooltip, PhysicsGauge, ThreatPanel } from "@/components/science/visualizations";
import { ScientificMap } from "@/components/science/scientific-map";
import { useStormtrace } from "@/components/stormtrace-provider";
import { useAlert, useAlerts, useBackendHealth, useMetrics, useReplayEvents, useSyncPipeline } from "@/hooks/use-stormtrace";
import { API_BASE_URL } from "@/lib/api";
import { resultMetrics, severityLabel } from "@/lib/pipeline";
import type { Alert, Severity } from "@/lib/types";

const displayEvent = (event: string) => event.replaceAll("_", " ").replace(/\b\w/g, (c) => c.toUpperCase());

export function CommandCenterPage() {
  const storm = useStormtrace();
  const result = storm.currentResult;
  const eventName = storm.jobs[0]?.eventName;
  return <><PageHeading eyebrow="Operational overview" title="Command Center" description="Spherical anomaly tracking, amplitude-preserving downscaling and physics-aware alerting in one auditable view." action={<div className="flex gap-2"><Button variant="outline" asChild><Link to="/historical-replay">Replay cases</Link></Button><Button onClick={() => storm.startReplay()} disabled={storm.isStarting}><Play /> Run demonstration</Button></div>} />
    <div className="mb-4 flex flex-wrap items-center justify-between gap-3 border border-primary/20 bg-primary/5 px-4 py-3"><div><span className="mr-3 text-[10px] font-bold uppercase text-primary">Historical replay default</span><span className="text-xs text-muted-foreground">Reproducible offline-safe inference · Synthetic multivariable ensemble</span></div><span className="data-mode">Simulated / synthetic demo data</span></div>
    {storm.currentJob && <div className="mb-4"><PipelineTimeline job={storm.currentJob} onRetry={() => storm.mode === "replay" ? storm.startReplay() : storm.startLive()} /></div>}
    <div className="grid gap-4 xl:grid-cols-[minmax(0,1.8fr)_minmax(290px,.7fr)]"><ScientificMap result={result} /><ThreatPanel result={result} eventName={eventName} /></div>
    <div className="mt-4 grid gap-px overflow-hidden border border-border bg-border grid-cols-2 md:grid-cols-4 xl:grid-cols-8">{resultMetrics(result).map(([label,value]) => <MetricTooltip key={label} label={label} value={value} description={metricDescription(label)} />)}</div>
    <div className="mt-4 grid gap-4 xl:grid-cols-[1.3fr_.7fr]"><ForecastTimeline result={result} /><PhysicsGauge result={result} /></div>
  </>;
}

export function LiveAnalysisPage() {
  const storm = useStormtrace();
  return <><PageHeading eyebrow="Asynchronous pipeline" title="Live Analysis" description="Start a fresh synthetic ensemble run. The current backend does not yet ingest live operational NEPS-G data." action={<Button onClick={storm.startLive} disabled={storm.isStarting}>{storm.isStarting ? <LoaderCircle className="animate-spin" /> : <Play />} Run live analysis</Button>} /><HonestyNote /><PipelineTimeline job={storm.currentJob} onRetry={storm.startLive} />{storm.currentResult && <div className="mt-4 grid gap-4 lg:grid-cols-2"><ThreatPanel result={storm.currentResult} eventName="live_run" /><JsonPanel value={storm.currentResult} /></div>}</>;
}

export function ReplayPage() {
  const storm = useStormtrace();
  const events = useReplayEvents();
  return <><PageHeading eyebrow="Judge demo mode" title="Historical Replay" description="Fixed-seed, reproducible pipeline execution using synthetic development data named for demonstration cases." action={<span className="data-mode">Offline-safe path</span>} /><div className="grid gap-4 xl:grid-cols-[360px_1fr]"><section className="panel p-5"><div className="data-label">Select replay case</div><div className="mt-4 space-y-2">{events.data?.available_events.map((event) => <button key={event} onClick={() => storm.setSelectedReplay(event)} className={`w-full border p-4 text-left transition-colors ${storm.selectedReplay === event ? "border-primary bg-primary/10" : "border-border hover:bg-accent"}`}><div className="text-sm font-semibold">{displayEvent(event)}</div><div className="mt-1 text-[10px] uppercase text-muted-foreground">Fixed seed · synthetic replay</div></button>)}</div>{events.isError && <ErrorState message="Replay events could not be loaded." retry={() => events.refetch()} />}<Button className="mt-4 w-full" onClick={() => storm.startReplay()} disabled={storm.isStarting || events.isError}><Sparkles /> Auto play demo</Button><p className="mt-4 text-[10px] leading-relaxed text-muted-foreground">Autoplay follows real backend stages. It never manufactures intermediate calculations.</p></section><div><PipelineTimeline job={storm.currentJob} onRetry={() => storm.startReplay()} /><div className="mt-4"><ForecastTimeline result={storm.currentResult} /></div></div></div></>;
}

export function TrackingPage() {
  const { currentResult } = useStormtrace();
  return <><PageHeading eyebrow="Stage 1" title="Anomaly Tracking" description="Mesh-native message passing isolates anomalous nodes and links clusters into a moving 4D object across D+3 to D+10." /><div className="grid gap-4 xl:grid-cols-[1.2fr_.65fr_.85fr]"><MeshField result={currentResult} compact /><section className="panel grid place-items-center p-5 text-center"><div><div className="data-label">EFI analysis</div><div className="my-6 font-mono text-6xl text-primary">{currentResult ? `+${currentResult.efi_peak.toFixed(2)}` : "—"}</div><p className="text-xs text-muted-foreground">Extreme Forecast Index relative to the synthetic climatological baseline.</p></div></section><ForecastTimeline result={currentResult} /></div><div className="mt-4 grid gap-4 lg:grid-cols-[1.5fr_.5fr]"><LossChart result={currentResult} /><section className="panel p-4"><div className="data-label">4D bounding box</div>{currentResult ? <div className="mt-4 grid grid-cols-2 gap-3 font-mono text-xs">{Object.entries(currentResult.bounding_box).map(([key,value]) => <div key={key} className="metric-mini"><span>{key}</span><strong>{Number(value).toFixed(Number.isInteger(value) ? 0 : 3)}</strong></div>)}</div> : <EmptyResult />}</section></div></>;
}

export function DownscalingPage() {
  const { currentResult: result } = useStormtrace();
  const peaks = [{name:"Raw / coarse",value: result?.unet_peak},{name:"U-Net baseline",value:result?.unet_peak},{name:"Stormtrace diffusion",value:result?.diffusion_peak}];
  return <><PageHeading eyebrow="Stage 2" title="Amplitude-Preserving Downscaling" description="A synchronized comparison of the 12 km coarse field, regression baseline and conditional diffusion output." /><div className="grid gap-3 lg:grid-cols-3">{peaks.map((item,index) => <section key={item.name} className="field-panel"><div className="flex justify-between border-b border-border p-3"><div><div className="data-label">Panel {String.fromCharCode(65+index)}</div><div className="mt-1 text-sm font-bold uppercase">{item.name}</div></div><span className="font-mono text-xs text-muted-foreground">{index ? "12 km → 5 km" : "12 km"}</span></div><FieldPattern strength={item.value} diffusion={index === 2} /><div className="flex justify-between p-3 text-xs"><span className="text-muted-foreground">Extreme peak</span><strong className="font-mono">{item.value?.toFixed(3) ?? "—"}</strong></div></section>)}</div><section className="panel mt-4 p-5"><div className="grid gap-6 lg:grid-cols-[1fr_1.4fr]"><div><div className="data-label">Why diffusion?</div><h2 className="mt-2 font-display text-xl font-semibold">Preserving extreme-value structure</h2><p className="mt-3 text-sm leading-relaxed text-muted-foreground">Regression-based downscaling can smooth extreme peaks toward the mean. STORMTRACE uses conditional diffusion to preserve extreme-value structure.</p></div><div className="space-y-4">{[["U-Net peak",result?.unet_peak],["Diffusion peak",result?.diffusion_peak]].map(([label,value]) => <div key={label as string}><div className="mb-1 flex justify-between text-[10px] uppercase"><span>{label}</span><span className="font-mono">{value ?? "—"}</span></div><div className="h-3 bg-muted"><div className="h-full bg-primary" style={{width: result ? `${Math.min(100, Number(value) / Math.max(result.diffusion_peak,result.unet_peak) * 100)}%` : "0%"}} /></div></div>)}<div className="border-t border-border pt-3"><span className="data-label">Amplitude gain</span><strong className="ml-4 font-mono text-2xl text-primary">{result ? `${result.amplitude_gain_pct.toFixed(1)}%` : "—"}</strong></div></div></div></section></>;
}

export function PhysicsPage() { const { currentResult } = useStormtrace(); return <><PageHeading eyebrow="Scientific validation" title="Physics Validation" description="Post-hoc ensemble agreement and moisture-convergence consistency, represented without claiming a hard physical guarantee." /><PhysicsGauge result={currentResult} /><div className="mt-4 grid gap-4 md:grid-cols-3">{[["Ensemble agreement","Generated field compared with the synthetic ensemble envelope."],["Conservation consistency","Moisture convergence consistency between coarse and generated fields."],["Model confidence","Severity confidence after physics-aware downgrade logic."]].map(([title,body]) => <section key={title} className="panel p-4"><CheckCircle2 className="mb-4 size-5 text-primary"/><h2 className="text-sm font-semibold">{title}</h2><p className="mt-2 text-xs leading-relaxed text-muted-foreground">{body}</p></section>)}</div></>; }

export function AlertCenterPage() {
  const [severity,setSeverity] = useState<Severity | "all">("all"); const [event,setEvent] = useState(""); const [search,setSearch] = useState(""); const [limit,setLimit] = useState(12); const [selected,setSelected] = useState<number|null>(null);
  const query = useAlerts({limit, ...(severity !== "all" ? {severity} : {}), ...(event ? {event_name:event} : {})});
  const rows = useMemo(() => (query.data ?? []).filter((a) => a.event_name.toLowerCase().includes(search.toLowerCase())),[query.data,search]);
  return <><PageHeading eyebrow="Persisted records" title="Alert Center" description="Backend-filtered alert records with authoritative detail retrieval." /><div className="mb-4 grid gap-2 md:grid-cols-[1fr_180px_220px_auto]"><div className="relative"><Search className="absolute left-3 top-2.5 size-4 text-muted-foreground"/><Input className="pl-9" value={search} onChange={(e)=>setSearch(e.target.value)} placeholder="Search loaded event names" /></div><Select value={severity} onValueChange={(v)=>setSeverity(v as Severity|"all")}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">All severities</SelectItem><SelectItem value="low">Low</SelectItem><SelectItem value="moderate">Moderate</SelectItem><SelectItem value="severe">Severe</SelectItem></SelectContent></Select><Input value={event} onChange={(e)=>setEvent(e.target.value)} placeholder="Exact event filter"/><Button variant="outline" onClick={()=>query.refetch()}><RefreshCw/> Refresh</Button></div>{query.isError ? <ErrorState message="Alerts could not be loaded." retry={()=>query.refetch()} /> : rows.length ? <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{rows.map((alert)=><AlertCard key={alert.id} alert={alert} onOpen={()=>setSelected(alert.id)} />)}</div> : <section className="panel grid min-h-60 place-items-center text-center"><div><AlertCircle className="mx-auto mb-3 text-muted-foreground"/><h2 className="text-sm font-semibold">No alerts yet</h2><p className="mt-1 text-xs text-muted-foreground">Run an analysis or launch Historical Replay.</p></div></section>} {rows.length >= limit && limit < 200 && <Button className="mt-4" variant="outline" onClick={()=>setLimit((v)=>Math.min(200,v+12))}>Load more</Button>}<AlertDetail id={selected} close={()=>setSelected(null)} /></>;
}

export function VerificationPage() {
  const metrics = useMetrics(); const data = metrics.data ? Object.entries(metrics.data.by_severity).map(([name,value])=>({name,value})) : [];
  return <><PageHeading eyebrow="Backend aggregates" title="Model Verification" description="Only currently exposed evidence is shown. Tracking recall and false-alarm rate remain unavailable from the API." action={<Button variant="outline" onClick={()=>metrics.refetch()}><RefreshCw/> Refresh</Button>} />{metrics.isError ? <ErrorState message="Verification metrics could not be loaded." retry={()=>metrics.refetch()} /> : <div className="grid gap-4 lg:grid-cols-[.7fr_1.3fr]"><div className="grid gap-3 sm:grid-cols-3 lg:grid-cols-1"><MetricCard label="Total alerts" value={metrics.data?.total_alerts}/><MetricCard label="Average physics score" value={metrics.data?.avg_physics_score}/><MetricCard label="Avg diffusion vs U-Net gain" value={metrics.data ? `${metrics.data.avg_diffusion_vs_unet_amplitude_gain_pct.toFixed(2)}%` : undefined}/></div><section className="panel p-5"><div className="data-label">Severity distribution</div><div className="mt-4 h-72">{data.length ? <ResponsiveContainer width="100%" height="100%"><BarChart data={data}><CartesianGrid stroke="var(--border)" vertical={false}/><XAxis dataKey="name" stroke="var(--muted-foreground)" fontSize={10}/><YAxis allowDecimals={false} stroke="var(--muted-foreground)" fontSize={10}/><ChartTooltip contentStyle={{background:"var(--card)",border:"1px solid var(--border)"}}/><Bar dataKey="value" fill="var(--primary)" radius={[2,2,0,0]}/></BarChart></ResponsiveContainer> : <EmptyResult />}</div></section></div>}</>;
}

export function SystemPage() {
  const health = useBackendHealth(); const storm = useStormtrace(); const sync = useSyncPipeline();
  const hydrated = useHydrated();
  const connected = hydrated && health.isSuccess;
  const endpoints = ["GET /health","POST /pipeline/run","GET /pipeline/status/{job_id}","POST /pipeline/run_sync","POST /replay/{event_key}","GET /replay/events","GET /alerts/latest","GET /alerts/{alert_id}","GET /metrics"];
  return <><PageHeading eyebrow="Developer operations" title="System / API" description="Connection diagnostics, in-session jobs, endpoint catalog and raw pipeline payloads." /><div className="grid gap-4 xl:grid-cols-[.8fr_1.2fr]"><section className="panel p-5"><div className="data-label">Connection</div><div className="mt-4 space-y-3"><SystemRow label="Backend URL" value={API_BASE_URL}/><SystemRow label="Status" value={connected ? "Connected" : "Unreachable"}/><SystemRow label="API version" value={hydrated ? health.data?.version ?? "—" : "—"}/><SystemRow label="Health message" value={hydrated ? health.data?.status ?? "—" : "—"}/></div><Button className="mt-5" variant="outline" onClick={()=>health.refetch()}><RefreshCw/> Retry connection</Button></section><section className="panel p-5"><div className="data-label">Recent jobs · current browser session</div><div className="mt-4 space-y-2">{storm.jobs.length ? storm.jobs.map((job)=><div key={job.id} className="grid grid-cols-[1fr_auto] gap-3 border-b border-border py-2 text-xs"><div><div className="font-mono">{job.id}</div><div className="mt-1 text-[10px] uppercase text-muted-foreground">{displayEvent(job.eventName)} · {job.mode}</div></div><span className="font-mono uppercase text-primary">{job.status}</span></div>) : <EmptyResult />}</div></section></div><div className="mt-4 grid gap-4 xl:grid-cols-[.8fr_1.2fr]"><section className="panel p-5"><div className="data-label">Endpoints available</div><div className="mt-4 space-y-2 font-mono text-[10px]">{endpoints.map((e)=><div key={e} className="border-l-2 border-primary/30 bg-muted/30 p-2">{e}</div>)}</div><div className="mt-6 border border-destructive/30 bg-destructive/5 p-4"><div className="flex gap-2 text-xs font-bold text-destructive"><ShieldAlert className="size-4"/> Developer / Advanced</div><p className="my-3 text-xs text-muted-foreground">Blocking execution — not recommended for normal dashboard operation.</p><Button variant="destructive" size="sm" disabled={sync.isPending} onClick={()=>sync.mutate({event_name:"live_run",seed:null},{onSuccess:(result)=>toast.success(`Sync alert #${result.alert_id} complete`)})}>{sync.isPending ? <LoaderCircle className="animate-spin"/> : <Play/>} Run synchronous pipeline</Button></div></section><JsonPanel value={sync.data ?? storm.currentResult} /></div></>;
}

function JsonPanel({value}:{value:unknown}) { const text=value?JSON.stringify(value,null,2):"No completed pipeline payload in this session."; return <section className="panel overflow-hidden"><div className="flex items-center justify-between border-b border-border p-3"><div className="flex items-center gap-2 text-xs font-semibold"><Braces className="size-4 text-primary"/> Actual JSON response</div><Button variant="ghost" size="sm" onClick={()=>{navigator.clipboard.writeText(text);toast.success("JSON COPIED")}} disabled={!value}><Clipboard/> Copy JSON</Button></div><pre className="max-h-[520px] overflow-auto p-4 font-mono text-[10px] leading-relaxed text-muted-foreground">{text}</pre></section> }
function AlertCard({alert,onOpen}:{alert:Alert;onOpen:()=>void}) { return <button onClick={onOpen} className="panel p-4 text-left transition-colors hover:border-primary/50"><div className="flex justify-between"><span className={`severity severity-${alert.severity}`}>{severityLabel(alert.severity)}</span><span className="font-mono text-[10px] text-muted-foreground">ALERT #{alert.id}</span></div><h2 className="mt-4 font-display text-lg font-semibold">{displayEvent(alert.event_name)}</h2><div className="mt-4 grid grid-cols-2 gap-3 text-xs">{[["Peak",alert.peak_value],["EFI",alert.efi_peak],["Confidence",alert.confidence],["Physics",alert.physics_score]].map(([k,v])=><div key={k as string}><span className="data-label">{k}</span><div className="mt-1 font-mono">{v}</div></div>)}</div><div className="mt-4 flex justify-between border-t border-border pt-3 text-[10px] text-muted-foreground"><span>Mesh [{alert.centroid_row}, {alert.centroid_col}]</span><span>{alert.radius_km} km radius</span></div></button> }
function AlertDetail({id,close}:{id:number|null;close:()=>void}) { const detail=useAlert(id); return <Dialog open={id!==null} onOpenChange={(o)=>!o&&close()}><DialogContent className="max-w-2xl"><DialogHeader><DialogTitle>Authoritative alert record</DialogTitle><DialogDescription>Fetched directly from GET /alerts/{id}</DialogDescription></DialogHeader>{detail.isLoading?<LoaderCircle className="mx-auto animate-spin"/>:detail.data?<><AlertCard alert={detail.data} onOpen={()=>{}}/><JsonPanel value={detail.data}/></>:<ErrorState message="Alert record unavailable." retry={()=>detail.refetch()}/>}</DialogContent></Dialog> }
function ErrorState({message,retry}:{message:string;retry:()=>unknown}) { return <section className="panel grid min-h-48 place-items-center p-6 text-center"><div><CloudOff className="mx-auto mb-3 text-destructive"/><div className="text-sm font-semibold">STORMTRACE ENGINE UNREACHABLE</div><p className="my-2 text-xs text-muted-foreground">{message}</p><Button size="sm" variant="outline" onClick={()=>retry()}><RefreshCw/> Retry connection</Button></div></section> }
function EmptyResult(){return <div className="grid h-full min-h-24 place-items-center text-xs text-muted-foreground"><span>Awaiting a completed pipeline result.</span></div>}
function MetricCard({label,value}:{label:string;value:string|number|undefined}){return <section className="metric-cell border border-border"><div className="data-label">{label}</div><div className="mt-3 font-mono text-3xl">{value ?? "—"}</div></section>}
function SystemRow({label,value}:{label:string;value:string}){return <div className="grid grid-cols-[110px_1fr] gap-3 text-xs"><span className="text-muted-foreground">{label}</span><strong className="truncate font-mono">{value}</strong></div>}
function FieldPattern({strength,diffusion}:{strength?:number|undefined;diffusion?:boolean}){return <div className={`field-pattern ${diffusion?"field-diffusion":""}`}><div className="field-core" style={{transform:`scale(${strength?Math.min(1.4,.8+Math.abs(strength)%1):.8})`}}/><span>DEMO VISUALIZATION</span></div>}
function HonestyNote(){return <div className="mb-4 flex gap-3 border border-status-warn/30 bg-status-warn/5 p-4 text-xs text-muted-foreground"><Database className="size-4 shrink-0 text-status-warn"/><span><strong className="text-foreground">DATA MODE: SYNTHETIC / DEMO.</strong> Real NEPS-G, NCUM and ERA5/IMDAA ingestion are intended future data paths.</span></div>}
function metricDescription(label:string){return ({"EFI peak":"Maximum Extreme Forecast Index returned by the pipeline.","Diffusion peak":"Maximum conditional diffusion output.","U-Net peak":"Maximum regression baseline output.","Amplitude gain":"Diffusion peak relative to U-Net peak.","Physics score":"Combined ensemble agreement and moisture-convergence consistency.","Tracked points":"Mesh points contained in the 4D bounding box.","Forecast window":"Backend bounding-box timestep range mapped to D+3 through D+10.","Processing time":"Measured backend wall-clock runtime."} as Record<string,string>)[label] ?? label}