import { AlertTriangle, Check, Circle, LoaderCircle, RotateCcw } from "lucide-react";
import { motion } from "motion/react";
import { Button } from "@/components/ui/button";
import { PIPELINE_STAGES, stageFromProgress } from "@/lib/pipeline";
import type { PipelineJobStatus } from "@/lib/types";
import { cn } from "@/lib/utils";

export function PipelineTimeline({ job, onRetry }: { job: PipelineJobStatus | null; onRetry?: () => void }) {
  const current = job?.status === "done" ? 8 : stageFromProgress(job?.progress ?? "");
  if (!job) return <div className="panel grid min-h-60 place-items-center p-6 text-center"><div><Circle className="mx-auto mb-3 size-8 text-muted-foreground" /><p className="font-display text-sm font-semibold">ENGINE STANDBY</p><p className="mt-1 text-xs text-muted-foreground">Launch a live analysis or historical replay.</p></div></div>;
  return <section className="panel overflow-hidden" aria-live="polite"><div className="scanline" aria-hidden /><div className="flex flex-wrap items-center justify-between gap-3 border-b border-border p-4"><div><div className="text-[10px] font-bold uppercase text-primary">Stormtrace engine</div><div className="mt-1 flex items-center gap-2 font-mono text-xs"><span>{job.status === "failed" ? "PIPELINE FAILED" : job.status === "done" ? "EXECUTION COMPLETE" : "PROCESSING PIPELINE"}</span>{job.status === "running" && <LoaderCircle className="size-3 animate-spin text-primary" />}</div></div><div className="text-right"><div className="text-[10px] uppercase text-muted-foreground">Job ID</div><div className="font-mono text-xs">{job.job_id.slice(0, 13)}…</div></div></div>
    <div className="grid gap-px bg-border md:grid-cols-4 xl:grid-cols-8">{PIPELINE_STAGES.map((stage) => { const complete = current > stage.id || job.status === "done"; const running = current === stage.id && job.status === "running"; return <div key={stage.id} className="relative bg-card p-3"><div className="mb-4 flex items-center justify-between"><span className="font-mono text-[10px] text-muted-foreground">{String(stage.id).padStart(2,"0")}</span>{complete ? <Check className="size-3 text-status-ok" /> : running ? <motion.span className="size-2 rounded-full bg-primary" animate={{ opacity: [.35,1,.35], scale: [.8,1.25,.8] }} transition={{ repeat: Infinity, duration: 1.5 }} /> : <Circle className="size-2.5 text-muted-foreground/40" />}</div><div className={cn("text-[10px] font-bold uppercase", running ? "text-primary" : complete ? "text-foreground" : "text-muted-foreground")}>{stage.title}</div><div className="mt-1 text-[9px] leading-tight text-muted-foreground">{stage.detail}</div>{running && <motion.div className="absolute inset-x-0 bottom-0 h-px bg-primary" layoutId="stage-progress" />}</div>; })}</div>
    <div className="flex flex-wrap items-center justify-between gap-2 p-3 text-[10px]"><span className="font-mono text-muted-foreground">{job.status === "running" ? `STEP ${Math.max(current,1)} OF 8 · ${job.progress}` : job.status.toUpperCase()}</span>{job.status === "failed" && <Button size="sm" variant="destructive" onClick={onRetry}><RotateCcw /> Retry</Button>}</div>{job.status === "failed" && <details className="border-t border-destructive/30 p-3"><summary className="cursor-pointer text-xs text-destructive"><AlertTriangle className="mr-2 inline size-3" />Developer error detail</summary><pre className="mt-3 overflow-auto whitespace-pre-wrap bg-muted p-3 text-[10px] text-muted-foreground">{job.error}</pre></details>}</section>;
}