import { useMemo, useState } from "react";
import { motion } from "motion/react";
import { Area, AreaChart, ResponsiveContainer, Tooltip as ChartTooltip, XAxis, YAxis } from "recharts";
import { Crosshair, Expand, Info, MapPinned } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Tooltip, TooltipContent, TooltipTrigger } from "@/components/ui/tooltip";
import { physicsStatus, severityLabel } from "@/lib/pipeline";
import type { PipelineResult } from "@/lib/types";

export function MeshField({ result, compact = false }: { result?: PipelineResult | undefined; compact?: boolean }) {
  const nodes = useMemo(() => Array.from({ length: compact ? 48 : 90 }, (_, i) => ({ x: 8 + ((i * 37) % 84), y: 8 + ((i * 53) % 80), hot: result ? i % Math.max(4, 10 - Math.round(result.efi_peak * 5)) === 0 : false })), [result, compact]);
  return <div className="mesh-field relative min-h-72 overflow-hidden border border-border bg-map"><div className="absolute left-4 top-4 z-10"><div className="data-label">Mesh coordinate field</div><div className="mt-1 font-mono text-xs text-map-foreground">{result ? `[${result.centroid_row}, ${result.centroid_col}]` : "AWAITING RESULT"}</div></div><div className="absolute right-3 top-3 z-10"><Button variant="ghost" size="icon" aria-label="Expand visualization"><Expand /></Button></div><svg viewBox="0 0 100 100" className="absolute inset-0 size-full" aria-label="Spherical mesh demo visualization">{nodes.map((node, i) => { const next = nodes[(i + 7) % nodes.length]; return next ? <line key={`l-${i}`} x1={node.x} y1={node.y} x2={next.x} y2={next.y} className="mesh-line" /> : null; })}{nodes.map((node, i) => node.hot ? <motion.circle key={i} cx={node.x} cy={node.y} r={1.15} className="mesh-node-hot" animate={{ opacity: [.5,1,.5] }} transition={{ repeat: Infinity, duration: 2 + (i % 4) * .3 }} /> : <circle key={i} cx={node.x} cy={node.y} r={.42} className="mesh-node" />)}</svg>{result && <div className="absolute bottom-4 right-4 flex items-center gap-3 border border-severity-severe/30 bg-background/80 px-3 py-2 backdrop-blur"><span className="threat-pulse"><Crosshair className="size-4 text-severity-severe" /></span><div><div className="text-[9px] uppercase text-muted-foreground">5 km impact radius</div><div className="font-mono text-xs">Mesh centroid</div></div></div>}<div className="absolute bottom-3 left-3 text-[9px] uppercase text-map-muted">Demo visualization · no latitude / longitude supplied</div></div>;
}

export function ThreatPanel({ result, eventName }: { result?: PipelineResult | undefined; eventName?: string | undefined }) {
  return <section className="panel h-full p-4"><div className="flex items-start justify-between"><div><div className="data-label">Active threat</div><h2 className="mt-2 font-display text-xl font-semibold">{eventName ? eventName.replaceAll("_", " ") : "No active result"}</h2></div><span className={`severity severity-${result?.severity ?? "none"}`}>{severityLabel(result?.severity)}</span></div><div className="my-5 h-px bg-border" /><div className="grid grid-cols-2 gap-x-4 gap-y-5">{[["Peak value", result?.peak_value],["Confidence", result?.confidence],["EFI peak", result?.efi_peak],["Physics", result?.physics_score],["Impact radius", result ? `${result.radius_km} km` : undefined],["Centroid", result ? `[${result.centroid_row}, ${result.centroid_col}]` : undefined]].map(([label,value]) => <div key={label as string}><div className="data-label">{label}</div><div className="mt-1 font-mono text-lg">{value ?? "—"}</div></div>)}</div><div className="mt-5 border-t border-border pt-4 text-[10px] leading-relaxed text-muted-foreground"><Info className="mr-2 inline size-3" />Severity combines normalized amplitude, EFI and physics consistency. Low-confidence severe calls may be downgraded by the backend.</div></section>;
}

export function ForecastTimeline({ result }: { result?: PipelineResult | undefined }) {
  const [step, setStep] = useState(result?.bounding_box.t_start ?? 0);
  return <section className="panel p-4"><div className="mb-4 flex items-center justify-between"><div><div className="data-label">4D trajectory</div><div className="mt-1 text-sm font-semibold">D+3 → D+10 forecast window</div></div><span className="font-mono text-xs text-primary">D+{step + 3}</span></div><div className="relative flex justify-between before:absolute before:left-4 before:right-4 before:top-3 before:h-px before:bg-border">{Array.from({length:8},(_,i) => { const active = result && i >= result.bounding_box.t_start && i <= result.bounding_box.t_end; return <button key={i} onClick={() => setStep(i)} className="relative z-10 grid gap-2 text-center focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring" aria-label={`Forecast day plus ${i+3}`}><span className={`mx-auto size-6 rounded-full border grid place-items-center text-[8px] ${step === i ? "border-primary bg-primary text-primary-foreground" : active ? "border-severity-moderate bg-severity-moderate/20" : "border-border bg-card"}`}>{active ? "●" : ""}</span><span className="font-mono text-[9px]">D+{i+3}</span></button>; })}</div></section>;
}

export function LossChart({ result }: { result?: PipelineResult | undefined }) {
  const data = (result?.gnn_loss_history ?? []).map((loss,index) => ({ epoch:index+1, loss }));
  return <section className="panel p-4"><div className="data-label">GNN loss history</div><div className="mt-3 h-36">{data.length ? <ResponsiveContainer width="100%" height="100%"><AreaChart data={data}><defs><linearGradient id="loss" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="var(--primary)" stopOpacity=".45"/><stop offset="1" stopColor="var(--primary)" stopOpacity="0"/></linearGradient></defs><XAxis dataKey="epoch" hide/><YAxis hide domain={["dataMin","dataMax"]}/><ChartTooltip contentStyle={{background:"var(--card)",border:"1px solid var(--border)",fontSize:10}}/><Area type="monotone" dataKey="loss" stroke="var(--primary)" fill="url(#loss)" isAnimationActive /></AreaChart></ResponsiveContainer> : <div className="grid h-full place-items-center text-xs text-muted-foreground">Run a pipeline to reveal training loss.</div>}</div></section>;
}

export function PhysicsGauge({ result }: { result?: PipelineResult | undefined }) {
  const score = result?.physics_score ?? 0;
  return <section className="panel min-w-0 p-5"><div className="data-label">Physics consistency</div><div className="mt-5 grid min-w-0 gap-5 2xl:grid-cols-[180px_minmax(0,1fr)] 2xl:items-center"><div className="relative mx-auto grid size-36 place-items-center rounded-full" style={{ background: `conic-gradient(var(--primary) ${score * 360}deg, var(--muted) 0)` }}><div className="grid size-28 place-items-center rounded-full bg-card text-center"><div><div className="font-mono text-3xl">{result ? score.toFixed(2) : "—"}</div><div className="mt-1 text-[9px] uppercase text-muted-foreground">Consistency score</div></div></div></div><div className="min-w-0 space-y-4"><div><div className="data-label">Status</div><div className="mt-1 break-words text-lg font-bold text-primary">{physicsStatus(result?.physics_score)}</div></div><p className="text-xs leading-relaxed text-muted-foreground">The backend combines post-hoc ensemble agreement with moisture-convergence consistency. The generated field is penalized, not physically guaranteed.</p><div className="grid gap-3 sm:grid-cols-2"><div className="metric-mini"><span>Ensemble agreement</span><strong>{result ? "Included" : "—"}</strong></div><div className="metric-mini"><span>Conservation check</span><strong>{result ? "Included" : "—"}</strong></div></div></div></div></section>;
}

export function MetricTooltip({ label, description, value }: { label: string; description: string; value: string | number | undefined }) {
  return <Tooltip><TooltipTrigger asChild><div className="metric-cell" tabIndex={0}><div className="data-label">{label}</div><div className="mt-2 font-mono text-xl">{value ?? "—"}</div></div></TooltipTrigger><TooltipContent className="max-w-56">{description}</TooltipContent></Tooltip>;
}